/* Mock data — Module An Ninh (Security), Vinalogistics TTOS */

const SEC_PENDING = [
  {
    id: "AN-2026-0512",
    source: "external",       // external | internal
    kind: "Đăng ký người",
    sub: "Khách",
    name: "Nguyễn Văn An",
    org: "Công ty Petrolimex",
    idNo: "079xxx",
    mode: "ONE_TIME",         // ONE_TIME | PERMANENT
    date: "09/07/2026",
    when: "15 phút trước",
  },
  {
    id: "AN-2026-0511",
    source: "internal",
    dept: "P. Kinh doanh",
    kind: "Đăng ký xe",
    sub: "PERMANENT",
    name: "51H-99887 · Xe tải",
    org: "Cty Vận tải Miền Nam",
    driver: "Trần Văn B",
    mode: "Dài hạn",
    date: null,
    when: "1 giờ trước",
  },
  {
    id: "AN-2026-0509",
    source: "external",
    kind: "Đăng ký người",
    sub: "Nhà thầu",
    name: "Lê Thị Cẩm",
    org: "Công ty Xây dựng Hoà Phát",
    idNo: "052xxx",
    mode: "ONE_TIME",
    date: "10/07/2026",
    when: "2 giờ trước",
  },
  {
    id: "AN-2026-0507",
    source: "external",
    kind: "Đăng ký người",
    sub: "Khách",
    name: "Đặng Quốc Huy",
    org: "Công ty CP Vận tải biển Đông",
    idNo: "038xxx",
    mode: "ONE_TIME",
    date: "11/07/2026",
    when: "4 giờ trước",
  },
];

const SEC_ALERTS = [
  { id: "sa1", level: "danger",  icon: "🔴", text: "Camera CAM-GATE02-IN offline",        meta: "5 phút trước" },
  { id: "sa2", level: "warning", icon: "🟡", text: "Xe 60K-12345 quá giờ (18h30m)",        meta: "Xe tải" },
  { id: "sa3", level: "warning", icon: "🟡", text: "Xe 72C-99001 quá giờ (10h15m)",        meta: "Xe container" },
  { id: "sa4", level: "danger",  icon: "🔴", text: "Xe 51F-00123 không ra sau 48h",        meta: "CRITICAL" },
  { id: "sa5", level: "warning", icon: "🟡", text: "Chứng nhận đào tạo hết hạn: 5 người", meta: "Tuần này" },
  { id: "sa6", level: "warning", icon: "🟡", text: "Xe 15C-45678 quá giờ (3h40m)",         meta: "Xe con" },
];

const SEC_STATS = {
  peopleIn:   { value: 156, unit: "người", delta: "↑12 so hôm qua" },
  vehiclesIn: { value: 23,  unit: "xe",    breakdown: "Con: 8 · Tải: 12 · Container: 3" },
  today:      { value: 342, unit: "lượt",  breakdown: "Người: 256 · Xe: 86" },
  lpr:        { value: "96,2", unit: "%",  delta: "↑1,2% vs tuần trước" },
};

/* Traffic by hour — 06:00 → 18:00 */
const SEC_TRAFFIC = [
  { h: "06h", people: 12,  vehicles: 4 },
  { h: "07h", people: 38,  vehicles: 9 },
  { h: "08h", people: 46,  vehicles: 11 },
  { h: "09h", people: 22,  vehicles: 7 },
  { h: "10h", people: 18,  vehicles: 8 },
  { h: "11h", people: 15,  vehicles: 6 },
  { h: "12h", people: 28,  vehicles: 5 },
  { h: "13h", people: 20,  vehicles: 7 },
  { h: "14h", people: 16,  vehicles: 9 },
  { h: "15h", people: 14,  vehicles: 8 },
  { h: "16h", people: 19,  vehicles: 7 },
  { h: "17h", people: 21,  vehicles: 4 },
  { h: "18h", people: 7,   vehicles: 1 },
];

/* === Security officers (subset of PEOPLE reused via ids, plus dedicated guard roles) === */
const SEC_OFFICERS = [
  { id: "s1", name: "Đội trưởng Bảo vệ — Ca ngày",  short: "ĐB1", role: "Đội trưởng An ninh", dept: "An Ninh", color: 5 },
  { id: "s2", name: "Vũ Đình Khoa",                  short: "VĐK", role: "Nhân viên bảo vệ cổng 1", dept: "An Ninh", color: 6 },
  { id: "s3", name: "Ngô Thị Hạnh",                  short: "NTH", role: "Nhân viên bảo vệ cổng 2", dept: "An Ninh", color: 4 },
];
const SEC_ME = SEC_OFFICERS[0];

/* === Đăng ký người/xe — hàng chờ duyệt đầy đủ (list + detail) === */
const SEC_APPROVALS = [
  {
    id: "AN-2026-0512",
    kind: "person",
    source: "external",
    sub: "Khách",
    name: "Nguyễn Văn An",
    org: "Công ty Petrolimex",
    idNo: "079xxxxxxxxx",
    purpose: "Làm việc với P. Kinh doanh về hợp đồng vận chuyển xăng dầu",
    host: "u5",
    mode: "ONE_TIME",
    validFrom: "09/07/2026 08:00",
    validTo: "09/07/2026 18:00",
    createdAt: "08/07/2026 09:45",
    priority: "normal",
    status: "current",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "current", at: null, note: null },
    ],
    files: [{ name: "CCCD_NguyenVanAn.jpg", size: "1.1 MB", type: "jpg" }],
    watchers: ["u5"],
  },
  {
    id: "AN-2026-0511",
    kind: "vehicle",
    source: "internal",
    dept: "P. Kinh doanh",
    sub: "PERMANENT",
    name: "51H-99887",
    vehicleType: "Xe tải",
    driver: "Trần Văn B",
    org: "Cty Vận tải Miền Nam",
    purpose: "Vận chuyển hàng hoá định kỳ vào kho Đình Vũ",
    mode: "Dài hạn",
    validFrom: "01/07/2026",
    validTo: "31/12/2026",
    createdAt: "08/07/2026 08:20",
    priority: "priority",
    status: "current",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "current", at: null, note: null },
    ],
    files: [{ name: "GiayPhepLuuHanh_51H99887.pdf", size: "640 KB", type: "pdf" }],
    watchers: ["u5"],
  },
  {
    id: "AN-2026-0509",
    kind: "person",
    source: "external",
    sub: "Nhà thầu",
    name: "Lê Thị Cẩm",
    org: "Công ty Xây dựng Hoà Phát",
    idNo: "052xxxxxxxxx",
    purpose: "Thi công sửa chữa mái kho số 3",
    host: "u7",
    mode: "ONE_TIME",
    validFrom: "10/07/2026 07:00",
    validTo: "10/07/2026 17:00",
    createdAt: "08/07/2026 06:55",
    priority: "normal",
    status: "current",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "current", at: null, note: null },
    ],
    files: [],
    watchers: ["u7"],
  },
  {
    id: "AN-2026-0507",
    kind: "person",
    source: "external",
    sub: "Khách",
    name: "Đặng Quốc Huy",
    org: "Công ty CP Vận tải biển Đông",
    idNo: "038xxxxxxxxx",
    purpose: "Khảo sát bến phao cho hợp đồng thuê tàu Q3",
    host: "u5",
    mode: "ONE_TIME",
    validFrom: "11/07/2026 09:00",
    validTo: "11/07/2026 12:00",
    createdAt: "08/07/2026 05:30",
    priority: "normal",
    status: "current",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "current", at: null, note: null },
    ],
    files: [],
    watchers: [],
  },
  {
    id: "AN-2026-0505",
    kind: "vehicle",
    source: "external",
    sub: "ONE_TIME",
    name: "15C-45678",
    vehicleType: "Xe con",
    driver: "Phạm Quang Vinh",
    org: "Khách vãng lai",
    purpose: "Đưa đón chuyên gia khảo sát cẩu",
    mode: "ONE_TIME",
    validFrom: "07/07/2026 08:00",
    validTo: "07/07/2026 18:00",
    createdAt: "07/07/2026 14:10",
    priority: "normal",
    status: "approved",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "approved", at: "07/07/2026 14:30", note: "Đồng ý, đã xác minh thông tin xe." },
    ],
    files: [],
    watchers: [],
  },
  {
    id: "AN-2026-0503",
    kind: "person",
    source: "external",
    sub: "Nhà thầu",
    name: "Bùi Văn Nam",
    org: "Công ty Bảo trì Thiết bị Cảng",
    idNo: "025xxxxxxxxx",
    purpose: "Bảo trì cẩu QC định kỳ — không đủ giấy chứng nhận an toàn còn hạn",
    host: "u7",
    mode: "ONE_TIME",
    validFrom: "06/07/2026 08:00",
    validTo: "06/07/2026 17:00",
    createdAt: "06/07/2026 07:40",
    priority: "normal",
    status: "rejected",
    currentStep: 1,
    chain: [
      { stepNo: 1, person: "s1", role: "Đội trưởng An ninh", state: "rejected", at: "06/07/2026 08:05", note: "Chứng nhận an toàn lao động đã hết hạn. Đề nghị bổ sung trước khi vào cảng." },
    ],
    files: [],
    watchers: ["u7"],
  },
];

/* === Người & xe hiện đang trong cảng === */
const SEC_PEOPLE_IN = [
  { id: "PIN-01", name: "Nguyễn Thành Đạt", org: "CTCP Thép Hoà Phát", type: "Nhà thầu", idNo: "036xxxxxxxxx", gate: "Cổng 1", checkIn: "07:12", host: "u3" },
  { id: "PIN-02", name: "Trịnh Bảo Long",   org: "Cảng vụ Hải Phòng",   type: "Khách",   idNo: "030xxxxxxxxx", gate: "Cổng 1", checkIn: "07:45", host: "u4" },
  { id: "PIN-03", name: "Đội thi công mái kho (6 người)", org: "Công ty Xây dựng Hoà Phát", type: "Nhà thầu", idNo: "—", gate: "Cổng 2", checkIn: "07:00", host: "u7" },
  { id: "PIN-04", name: "Hoàng Anh Dũng",   org: "Maersk Việt Nam",     type: "Khách",   idNo: "024xxxxxxxxx", gate: "Cổng 1", checkIn: "08:20", host: "u5" },
  { id: "PIN-05", name: "Vũ Quang Huy",     org: "Công ty CP Vận tải biển Đông", type: "Khách", idNo: "038xxxxxxxxx", gate: "Cổng 1", checkIn: "09:05", host: "u5" },
];

const SEC_VEHICLES_IN = [
  { id: "VIN-01", plate: "51H-99887",  type: "Xe tải",      org: "Cty Vận tải Miền Nam", driver: "Trần Văn B",    priority: "priority", gate: "Cổng 2", checkIn: "06:40", purpose: "Giao hàng kho Đình Vũ" },
  { id: "VIN-02", plate: "60K-12345",  type: "Xe tải",      org: "Cty TNHH Minh Phát",   driver: "Lê Văn Sơn",    priority: "normal",   gate: "Cổng 2", checkIn: "14:10", purpose: "Nhận hàng — quá giờ dự kiến" },
  { id: "VIN-03", plate: "72C-99001",  type: "Xe container",org: "Vinacomin",            driver: "Đỗ Văn Tùng",   priority: "normal",   gate: "Cổng 2", checkIn: "22:30", purpose: "Chuyển tải than cám" },
  { id: "VIN-04", plate: "29A-88990",  type: "Xe con",      org: "TCT Xăng dầu Quân đội",driver: "Ngô Thế Anh",   priority: "priority", gate: "Cổng 1", checkIn: "10:05", purpose: "Đón đoàn ký hợp đồng" },
  { id: "VIN-05", plate: "15C-77201",  type: "Xe con",      org: "Khách vãng lai",       driver: "Phạm Quang Vinh", priority: "normal", gate: "Cổng 1", checkIn: "08:00", purpose: "Đưa đón chuyên gia" },
];

/* === Sự cố === */
const SEC_INCIDENTS = [
  {
    id: "SC-2026-014",
    title: "Camera CAM-GATE02-IN mất tín hiệu",
    category: "Thiết bị",
    level: "danger",
    location: "Cổng 2 — làn vào",
    reportedBy: "s3",
    reportedAt: "08/07/2026 07:55",
    status: "open",
    description: "Camera giám sát làn vào cổng 2 mất tín hiệu từ 07:55, nghi do đứt cáp mạng sau đợt mưa lớn đêm qua. Đã chuyển sang quan sát thủ công tạm thời.",
    log: [
      { at: "08/07/2026 07:55", by: "s3", text: "Phát hiện camera mất tín hiệu, đã báo đội kỹ thuật." },
      { at: "08/07/2026 08:10", by: "s1", text: "Đã bố trí nhân viên trực thủ công tại làn vào trong lúc chờ khắc phục." },
    ],
  },
  {
    id: "SC-2026-013",
    title: "Xe 51F-00123 không rời cảng sau 48 giờ",
    category: "Vi phạm quy định",
    level: "danger",
    location: "Bãi xe container — khu B",
    reportedBy: "s2",
    reportedAt: "08/07/2026 06:30",
    status: "investigating",
    description: "Xe container 51F-00123 vào cảng ngày 06/07 lúc 08:00 nhưng chưa rời đi sau 48 giờ, vượt quá thời gian lưu bãi cho phép. Đang liên hệ đơn vị vận tải để xác minh lý do.",
    log: [
      { at: "08/07/2026 06:30", by: "s2", text: "Phát hiện xe quá hạn lưu bãi, đã lập biên bản." },
      { at: "08/07/2026 09:00", by: "s1", text: "Đã liên hệ đơn vị vận tải, chờ phản hồi trong hôm nay." },
    ],
  },
  {
    id: "SC-2026-012",
    title: "Xe 60K-12345 quá giờ lưu bãi dự kiến",
    category: "Vi phạm quy định",
    level: "warning",
    location: "Cổng 2",
    reportedBy: "s2",
    reportedAt: "07/07/2026 20:00",
    status: "open",
    description: "Xe tải 60K-12345 đăng ký thời gian ra trong ngày nhưng hiện đã quá 18h30 phút so với kế hoạch.",
    log: [
      { at: "07/07/2026 20:00", by: "s2", text: "Ghi nhận xe quá giờ, đã thông báo tài xế." },
    ],
  },
  {
    id: "SC-2026-011",
    title: "Xe 72C-99001 quá giờ lưu bãi dự kiến",
    category: "Vi phạm quy định",
    level: "warning",
    location: "Cổng 2",
    reportedBy: "s3",
    reportedAt: "07/07/2026 12:00",
    status: "open",
    description: "Xe container 72C-99001 quá thời gian dự kiến rời cảng 10 giờ 15 phút.",
    log: [
      { at: "07/07/2026 12:00", by: "s3", text: "Ghi nhận xe quá giờ, đang chờ xác nhận từ đơn vị vận tải." },
    ],
  },
  {
    id: "SC-2026-010",
    title: "Chứng nhận đào tạo an ninh hết hạn: 5 người",
    category: "Nhân sự",
    level: "warning",
    location: "Toàn cảng",
    reportedBy: "s1",
    reportedAt: "06/07/2026 09:00",
    status: "open",
    description: "5 nhân viên bảo vệ có chứng nhận đào tạo an ninh cảng hết hạn trong tuần này, cần đăng ký đào tạo lại để tiếp tục trực ca.",
    log: [
      { at: "06/07/2026 09:00", by: "s1", text: "Đã lập danh sách và gửi đăng ký lớp đào tạo lại." },
    ],
  },
  {
    id: "SC-2026-009",
    title: "Phát hiện người lạ tại khu vực bãi container",
    category: "An ninh",
    level: "danger",
    location: "Bãi container — khu A",
    reportedBy: "s2",
    reportedAt: "05/07/2026 23:10",
    status: "resolved",
    description: "Phát hiện một người không đeo thẻ ra vào tại khu bãi container lúc 23:10. Đã kiểm tra, xác minh là nhân viên ca đêm quên đeo thẻ.",
    log: [
      { at: "05/07/2026 23:10", by: "s2", text: "Phát hiện và tiếp cận kiểm tra." },
      { at: "05/07/2026 23:20", by: "s2", text: "Xác minh là nhân viên nội bộ, đã nhắc nhở và đóng sự cố." },
    ],
  },
];

/* === Đăng ký người ra/vào cảng — danh sách riêng (list/form/detail) === */
const PERSON_REGS = [
  {
    id: "PR-0128", name: "Trần Văn Bình", idNo: "079088xxxxxx", dob: "15/03/1985", phone: "0909 xxx xxx",
    org: "Công ty Petrolimex Hải Phòng", kind: "Khách", purpose: "Giao hàng",
    contact: "u5", mode: "ONE_TIME", validFrom: "08/07/2026", validTo: "15/07/2026",
    source: "internal", dept: "P. Kinh doanh", status: "active",
    training: { done: true, code: "ĐT-0045", date: "05/07/2026", expire: "05/07/2027" },
    history: [
      { date: "08/07/2026", in: "08:15", out: null, gate: "Cổng 1", dur: "Đang trong", guard: "Trần Minh" },
      { date: "07/07/2026", in: "09:30", out: "16:45", gate: "Cổng 2", dur: "7h 15m", guard: "Lê Quốc Bảo" },
    ],
    timeline: [
      { at: "08/07 08:00", icon: "🟢", text: "Kích hoạt (tự động)" },
      { at: "07/07 14:30", icon: "✅", text: "Phê duyệt bởi Anh Đức" },
      { at: "07/07 10:00", icon: "📝", text: "Tạo bởi Nguyễn Văn Hùng (P.Kinh doanh)" },
    ],
  },
  {
    id: "PR-0129", name: "Lê Thị Cẩm", idNo: "052xxxxxxxxx", dob: "22/11/1990", phone: "0912 xxx xxx",
    org: "Công ty Xây dựng Hoà Phát", kind: "Nhà thầu", purpose: "Sửa chữa",
    contact: "u7", mode: "ONE_TIME", validFrom: "10/07/2026", validTo: "10/07/2026",
    source: "external", dept: null, status: "pending",
    training: { done: false, code: null, date: null, expire: null },
    history: [],
    timeline: [{ at: "08/07 06:55", icon: "📝", text: "Tạo bởi Lê Thị Cẩm (đăng ký ngoài)" }],
  },
  {
    id: "PR-0125", name: "Nguyễn Hoàng An", idNo: "038xxxxxxxxx", dob: "02/06/1988", phone: "0977 xxx xxx",
    org: "VNL", kind: "Tài xế", purpose: "Công tác",
    contact: "u3", mode: "RECURRING", validFrom: "01/06/2026", validTo: "31/12/2026",
    days: ["T2","T3","T4","T5","T6"], hours: "06:00–18:00",
    source: "internal", dept: "ATCL", status: "active",
    training: { done: true, code: "ĐT-0040", date: "01/06/2026", expire: "01/06/2027" },
    history: [{ date: "08/07/2026", in: "06:20", out: null, gate: "Cổng 1", dur: "Đang trong", guard: "Trần Minh" }],
    timeline: [
      { at: "01/06 06:00", icon: "🟢", text: "Kích hoạt (tự động)" },
      { at: "31/05 09:00", icon: "📝", text: "Tạo bởi Phạm Minh Tuấn (ATCL)" },
    ],
  },
  {
    id: "PR-0120", name: "Phạm Văn Đức", idNo: "074xxxxxxxxx", dob: "10/01/1982", phone: "0933 xxx xxx",
    org: "Cty Vận tải ABC", kind: "Tài xế", purpose: "Giao hàng",
    contact: "u3", mode: "PERMANENT", validFrom: "01/07/2026", validTo: "31/12/2026",
    source: "internal", dept: "P. Kỹ thuật", status: "active",
    training: { done: true, code: "ĐT-0031", date: "20/06/2026", expire: "20/06/2027" },
    history: [{ date: "07/07/2026", in: "07:00", out: "15:10", gate: "Cổng 2", dur: "8h 10m", guard: "Ngô Thị Hạnh" }],
    timeline: [
      { at: "01/07 07:00", icon: "🟢", text: "Kích hoạt sau phê duyệt dài hạn" },
      { at: "30/06 15:00", icon: "✅", text: "Phê duyệt bởi Anh Đức" },
      { at: "29/06 08:00", icon: "📝", text: "Tạo bởi Đặng Ngọc Sơn (P.Kỹ thuật)" },
    ],
  },
  {
    id: "PR-0117", name: "Đỗ Thị Ngọc", idNo: "025xxxxxxxxx", dob: "18/09/1995", phone: "0966 xxx xxx",
    org: "Công ty Bảo trì Thiết bị Cảng", kind: "Nhà thầu", purpose: "Sửa chữa",
    contact: "u7", mode: "ONE_TIME", validFrom: "01/07/2026", validTo: "03/07/2026",
    source: "external", dept: null, status: "expired",
    training: { done: true, code: "ĐT-0028", date: "28/06/2026", expire: "28/06/2027" },
    history: [{ date: "02/07/2026", in: "08:00", out: "17:30", gate: "Cổng 1", dur: "9h 30m", guard: "Lê Quốc Bảo" }],
    timeline: [{ at: "03/07 23:59", icon: "⚪", text: "Hết hiệu lực (tự động)" }],
  },
  {
    id: "PR-0110", name: "Bùi Văn Nam", idNo: "025xxxxxxxxx", dob: "05/05/1979", phone: "0944 xxx xxx",
    org: "Công ty Bảo trì Thiết bị Cảng", kind: "Nhà thầu", purpose: "Sửa chữa",
    contact: "u7", mode: "ONE_TIME", validFrom: "06/07/2026", validTo: "06/07/2026",
    source: "external", dept: null, status: "rejected",
    training: { done: false, code: null, date: null, expire: null },
    history: [], reason: "Chứng nhận an toàn lao động đã hết hạn.",
    timeline: [{ at: "06/07 08:05", icon: "❌", text: "Từ chối bởi Anh Đức — Chứng nhận hết hạn" }],
  },
];

/* === Đăng ký xe ra/vào cảng — danh sách riêng === */
const VEHICLE_REGS = [
  {
    id: "VR-0042", plate: "51H-12345", vtype: "Xe con", container: null,
    priority: "priority", driver: "Nguyễn Văn A", driverId: "038xxxxxxxxx", phone: "0909 xxx xxx",
    org: "VNL", purpose: "Công tác", mode: "PERMANENT", validFrom: "01/07/2026", validTo: "31/12/2026",
    source: "internal", dept: "ATCL", status: "active",
  },
  {
    id: "VR-0088", plate: "60K-99887", vtype: "Xe tải", container: null,
    priority: "normal", driver: "Trần Văn B", driverId: "060xxxxxxxxx", phone: "0912 xxx xxx",
    org: "Cty Vận tải Miền Nam", purpose: "Giao hàng", mode: "ONE_TIME", validFrom: "09/07/2026", validTo: "09/07/2026",
    source: "external", dept: null, status: "pending",
  },
  {
    id: "VR-0076", plate: "72C-55123", vtype: "Xe container", container: "MSKU1234567",
    priority: "normal", driver: "Lê Văn C", driverId: "072xxxxxxxxx", phone: "0977 xxx xxx",
    org: "Cty Logistics HP", purpose: "Nhận hàng", mode: "RECURRING", validFrom: "01/07/2026", validTo: "31/12/2026",
    days: ["T2","T3","T4","T5","T6"], hours: "06:00–18:00",
    source: "internal", dept: "P. Kỹ thuật", status: "active",
  },
  {
    id: "VR-0065", plate: "29A-88990", vtype: "Xe con", container: null,
    priority: "priority", driver: "Ngô Thế Anh", driverId: "029xxxxxxxxx", phone: "0988 xxx xxx",
    org: "TCT Xăng dầu Quân đội", purpose: "Công tác", mode: "ONE_TIME", validFrom: "07/07/2026", validTo: "07/07/2026",
    source: "external", dept: null, status: "active",
  },
  {
    id: "VR-0050", plate: "15C-77201", vtype: "Xe con", container: null,
    priority: "normal", driver: "Phạm Quang Vinh", driverId: "015xxxxxxxxx", phone: "0966 xxx xxx",
    org: "Khách vãng lai", purpose: "Công tác", mode: "ONE_TIME", validFrom: "01/07/2026", validTo: "01/07/2026",
    source: "external", dept: null, status: "expired",
  },
  {
    id: "VR-0044", plate: "51F-00123", vtype: "Xe container", container: "TCLU9988776",
    priority: "normal", driver: "Đinh Văn Toàn", driverId: "051xxxxxxxxx", phone: "0955 xxx xxx",
    org: "Cty Vận tải Miền Trung", purpose: "Giao hàng", mode: "ONE_TIME", validFrom: "06/07/2026", validTo: "06/07/2026",
    source: "external", dept: null, status: "rejected", reason: "Thiếu giấy phép lưu hành hợp lệ.",
  },
];

Object.assign(window, {
  SEC_PENDING, SEC_ALERTS, SEC_STATS, SEC_TRAFFIC,
  SEC_OFFICERS, SEC_ME,
  SEC_APPROVALS, SEC_PEOPLE_IN, SEC_VEHICLES_IN, SEC_INCIDENTS,
  PERSON_REGS, VEHICLE_REGS,
});
